### ISSUE TITLE
Problems building on MacOS 12.6

### ISSUE THREAD

**Issue by FAnderl** [westes/flex#541]
When trying to build on MacOS 12.6 Monterey after running 
$ configure
$ make 

the following error is reported

---------------------------------------------------
skeletons.c:255:10: error: expected '}'
/* end */
         ^
skeletons.c:40:26: note: to match this '{'
const char *cpp_skel[] = {
                         ^
skeletons.c:252:2: error: expected ';' after top level declarator
}
---------------------------------------------------

**Comment by Mightyjo** [comment]
If you're building from git, did you run autogen.sh before configure?

**Comment by Mightyjo** [comment]
Sorry, answered too soon after waking up. Confused skeletons.c with another
file.

Are you building from git or a release tarball?

**Comment by FAnderl** [comment]
Hi, thanks for your answer. I am building from git. That might be the problem, right? Maybe I should have tried a release tarball first...
In the meantime I installed flex via brew. I can close the issue then. Thank you again!

**Comment by Mightyjo** [comment]
Building from git is no problem. Just needed to know what version of the
code to check for bugs.

I don't have a Mac to test on, and that line is doing something clever.

Which compiler are you using?

**Comment by Mightyjo** [comment]
Last question for this morning, what do you see in cpp-flex.h? It's a built
source file so it won't exist in a clean tree.

**Comment by FAnderl** [comment]
Sorry for the late answer. I am using the compiler 
**clang version 14.0.0 (clang-1400.0.29.102)**

You will find my cpp-flex.h attached. 

[cpp-flex.h.zip](https://github.com/westes/flex/files/9764706/cpp-flex.h.zip)
