### ISSUE TITLE
Option --yymore isn't documented

### ISSUE THREAD

**Issue by yurivict** [westes/flex#369]
It is only mentioned once in the C code:
```
$ grep -r -- --yymore work/
work/flex-2.6.4/src/options.c:	{"--yymore", OPT_YYMORE, 0}
```

Not in manpages, help, etc.

Version 2.6.4

**Comment by yurivict** [comment]
It isn't clear why does it create a broken C code when ```--yymore``` isn't used.

**Comment by westes** [comment]
Please provide an example that breaks. Provide a sample minimal lexer if relevant and what commands you used that demonstrate the break.

On Sunday, 24 June 2018,  1:06 am -0700, "yuri@FreeBSD" <notifications@github.com> wrote:

> It isn't clear why does it create a broken C code when ```--yymore``` isn't used.
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/369#issuecomment-399738019

-- 
Will Estes
westes575@gmail.com

**Comment by westes** [comment]
Can you provide either a url to a -minimal- example or attach a file to this issue? You listed a local path on an OS i don't run, so that provides no data to look at.

Can you provide the -command- you ran to generate the error?

On Sunday, 24 June 2018, 11:24 am -0700, "yuri@FreeBSD" <notifications@github.com> wrote:

> > Please provide an example that breaks.
> 
> The project that is part of kde4, ```kdevelop-pg-qt-1.0.0```, failed to build with flex-2.6.4.
> I had to add the patch that adds ```--yymore``` to the flex command to fix it.
> ```kdev-pg/kdev-pg-lexer.ll``` is the flex example there.
> ```
> /usr/ports/devel/kdevelop-pg-qt-kde4/work/kdevelop-pg-qt-1.0.0/kdev-pg/kdev-pg-lexer.ll:255:12: error: use of undeclared identifier 'yymore_used_but_not_detected'
> newline(); YYMORE;
>            ^
> ```
> 
> But also, there shouldn't be any undocumented options.
> 
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/369#issuecomment-399776755

-- 
Will Estes
westes575@gmail.com

**Comment by yurivict** [comment]
I can't come up with the minimal example.
All I know is that the line ```kdevelop-pg-qt-1.0.0/kdev-pg/kdev-pg-lexer.ll:255:12``` in the project kdevelop-pg-qt version 1.0.0 fails.

-----

You should document ```--yymore```. What is it for? Why does it change things?

**Comment by westes** [comment]
You have not provided:

- a lexer that fails
- a command to produce the error

Please do so or I will close the bug report since you have yet to produce something I can investigate.

On Sunday, 24 June 2018, 12:55 pm -0700, "yuri@FreeBSD" <notifications@github.com> wrote:

> I can't come up with the minimal example.
> All I know is that the line ```kdevelop-pg-qt-1.0.0/kdev-pg/kdev-pg-lexer.ll:255:12``` in the project kdevelop-pg-qt version 1.0.0 fails.
> 
> -----
> 
> You should document ```--yymore```. What is it for? Why does it change things?
> 
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/369#issuecomment-399783019

-- 
Will Estes
westes575@gmail.com

**Comment by yurivict** [comment]
1. configure with cmake
```
cmake -DCMAKE_C_COMPILER:STRING="cc"  -DCMAKE_CXX_COMPILER:STRING="c++"  -DCMAKE_C_FLAGS:STRING="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector -fno-strict-aliasing"  -DCMAKE_C_FLAGS_DEBUG:STRING="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector -fno-strict-aliasing"  -DCMAKE_C_FLAGS_RELEASE:STRING="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector -fno-strict-aliasing"  -DCMAKE_CXX_FLAGS:STRING="-O2 -pipe -fno-omit-frame-pointer -fstack-protector -fno-strict-aliasing -fno-omit-frame-pointer "  -DCMAKE_CXX_FLAGS_DEBUG:STRING="-O2 -pipe -fno-omit-frame-pointer -fstack-protector -fno-strict-aliasing -fno-omit-frame-pointer "  -DCMAKE_CXX_FLAGS_RELEASE:STRING="-O2 -pipe -fno-omit-frame-pointer -fstack-protector -fno-strict-aliasing -fno-omit-frame-pointer "  -DCMAKE_EXE_LINKER_FLAGS:STRING=" -fstack-protector"  -DCMAKE_MODULE_LINKER_FLAGS:STRING=" -fstack-protector"  -DCMAKE_SHARED_LINKER_FLAGS:STRING=" -fstack-protector"  -DCMAKE_INSTALL_PREFIX:PATH="/usr/local"  -DCMAKE_BUILD_TYPE:STRING="Release"  -DTHREADS_HAVE_PTHREAD_ARG:BOOL=YES  -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=YES  -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_PREFIX_PATH="/usr/local" -DKDE4_BUILD_TESTS:BOOL=OFF -DKDE_INSTALL_MANDIR:PATH="/usr/local/man" -DMAN_INSTALL_DIR:PATH="/usr/local/man"
```
2. build
```make```

**Comment by yurivict** [comment]
Here is the difference that ```--yymore``` makes in the output:

```

--- ./work.orig/.build/kdev-pg/kdev-pg-lexer.cc	2018-06-24 13:41:38.014165000 -0700
+++ ./work/.build/kdev-pg/kdev-pg-lexer.cc	2018-06-24 13:42:47.510919000 -0700
@@ -348,7 +348,8 @@
  */
 #define YY_DO_BEFORE_ACTION \
 	(yytext_ptr) = yy_bp; \
-	yyleng = (int) (yy_cp - yy_bp); \
+	(yytext_ptr) -= (yy_more_len); \
+	yyleng = (int) (yy_cp - (yytext_ptr)); \
 	(yy_hold_char) = *yy_cp; \
 	*yy_cp = '\0'; \
 	(yy_c_buf_p) = yy_cp;
@@ -1154,8 +1155,10 @@
 goto find_rule; \
 }
 
-#define yymore() yymore_used_but_not_detected
-#define YY_MORE_ADJ 0
+static int yy_more_flag = 0;
+static int yy_more_len = 0;
+#define yymore() ((yy_more_flag) = 1)
+#define YY_MORE_ADJ (yy_more_len)
 #define YY_RESTORE_YY_MORE_OFFSET
 char *yytext;
 #line 1 "/usr/ports/devel/kdevelop-pg-qt-kde4/work/kdevelop-pg-qt-1.0.0/kdev-pg/kdev-pg-lexer.ll"
@@ -1263,9 +1266,9 @@
 #include <unistd.h>
 #endif
 
-#line 1266 "/usr/ports/devel/kdevelop-pg-qt-kde4/work/.build/kdev-pg/kdev-pg-lexer.cc"
+#line 1269 "/usr/ports/devel/kdevelop-pg-qt-kde4/work/.build/kdev-pg/kdev-pg-lexer.cc"
 
-#line 1268 "/usr/ports/devel/kdevelop-pg-qt-kde4/work/.build/kdev-pg/kdev-pg-lexer.cc"
+#line 1271 "/usr/ports/devel/kdevelop-pg-qt-kde4/work/.build/kdev-pg/kdev-pg-lexer.cc"
 
 #define INITIAL 0
 #define CODE 1
@@ -1490,10 +1493,16 @@
 
 
 
-#line 1493 "/usr/ports/devel/kdevelop-pg-qt-kde4/work/.build/kdev-pg/kdev-pg-lexer.cc"
+#line 1496 "/usr/ports/devel/kdevelop-pg-qt-kde4/work/.build/kdev-pg/kdev-pg-lexer.cc"
 
 	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
 		{
+		(yy_more_len) = 0;
+		if ( (yy_more_flag) )
+			{
+			(yy_more_len) = (int) ((yy_c_buf_p) - (yytext_ptr));
+			(yy_more_flag) = 0;
+			}
 		yy_cp = (yy_c_buf_p);
 
 		/* Support of yytext. */
@@ -2365,7 +2374,7 @@
 #line 359 "/usr/ports/devel/kdevelop-pg-qt-kde4/work/kdevelop-pg-qt-1.0.0/kdev-pg/kdev-pg-lexer.ll"
 ECHO;
 	YY_BREAK
-#line 2368 "/usr/ports/devel/kdevelop-pg-qt-kde4/work/.build/kdev-pg/kdev-pg-lexer.cc"
+#line 2377 "/usr/ports/devel/kdevelop-pg-qt-kde4/work/.build/kdev-pg/kdev-pg-lexer.cc"
 			case YY_STATE_EOF(INITIAL):
 			case YY_STATE_EOF(PARSERCLASS):
 			case YY_STATE_EOF(RULE_PARAMETERS_HEADER):
```

Without ```--yymore``` it fails with the unknown symbol ```yymore_used_but_not_detected```.

**Comment by yurivict** [comment]
So it was supposedly a case of missing ```yymore```.  (How did it work before?) Now ```--yymore``` is required to auto-inject it (?). Did the definition of the lexer change so that yymore became required? Not sure what is going on here with ```--yymore``` being undocumented.

**Comment by jannick0** [comment]
* Looking at the repo https://github.com/KDE/kdevelop-pg-qt, the flex command line flag `--yymore` **is** set by `cmake` (see https://github.com/KDE/kdevelop-pg-qt/blob/6c0fbd7304d8720f5eeecae300c692d848436feb/kdev-pg/CMakeLists.txt#L70-L79): 
~~~
/* CMakeList.txt */
...
IF(FLEX_EXECUTABLE)
    # Add command to run the lexer.
    ADD_CUSTOM_COMMAND(
        OUTPUT  "${CMAKE_CURRENT_BINARY_DIR}/kdev-pg-lexer.cc"
        DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/kdev-pg-lexer.ll"
                 ${OPTIONAL_PARSER_HEADER_DEPENDENCY}
        COMMAND ${FLEX_EXECUTABLE}
        ARGS    --yymore --nounistd -o "${CMAKE_CURRENT_BINARY_DIR}/kdev-pg-lexer.cc"
                "${CMAKE_CURRENT_SOURCE_DIR}/kdev-pg-lexer.ll"
     )
...
~~~
* [flex docu, 3rd bullet](https://westes.github.io/flex/manual/Diagnostics.html#Diagnostics): If at compile time `yymore_used_but_not_detected` is undefined, it is recommended to use `%option yymore` for which the command line flag `--yymore` is equivalent.

So I am wondering why the flex flag `--yymore` (among others) is not set in your case, when using `cmake` with the `CMakeList.txt` as given above. And yes, this approach is already documented for the `%option` case.

**Comment by yurivict** [comment]
> So I am wondering why the flex flag --yymore (among others) is not set in your case

Because of the old version that is used for kde4.

**Comment by yurivict** [comment]
If there is no problem, then that's fine.

But please document ```--yymore```.  Every option should be documented.

**Comment by westes** [comment]
We welcome pull requests to fix things in flex. It's true that the manual needs a lot of work right now. Small fixes to the manual should be an ideal way to start contributing.

On Sunday, 24 June 2018,  2:19 pm -0700, "yuri@FreeBSD" <notifications@github.com> wrote:

> If there is no problem, then that's fine.
> 
> But please document ```--yymore```.  Every option should be documented.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/369#issuecomment-399788424

-- 
Will Estes
westes575@gmail.com
