### ISSUE TITLE
Cannot built flex with MinGW - configure says all fine...

### ISSUE THREAD

**Issue by GitMensch** [westes/flex#188]
configure.ac misses a check for `HAVE_SYS_WAIT_H`:

    flexdef.h:72:22: fatal error: sys/wait.h: No such file or directory

I guess it may be possible to build flex without this if filter.c and main.c are changed? If not: configure should abort if it isn't found.

configure.ac checks for `HAVE_REGEX_H` and includes the check in flexdef.h for the include but not for the function declarations of regex.c later:

    flexdef.h:1138:1: error: unknown type name 'regex_t'

I guess it won't be possible at all to build flex without this - in this case configure should error if the header isn't available (it is available for MinGW/MSYS).

**Comment by westes** [comment]
See #185.

**Comment by GitMensch** [comment]
Yes, c14a8c3 fixes this issue.

**Comment by Explorer09** [comment]
@GitMensch Is there any regression with my change in c14a8c38693e8c91a47e955648a56cff707b70d4 when building in MinGW, or is your complaint exactly the same as what I addressed in #185?

**Comment by westes** [comment]
No, there was not. The poster was unaware of the fix provided in #185 since that happened post-2.6.3 and 2.6.4 is not out yet.

On Friday, 24 February 2017,  8:31 pm -0800, "Kang-Che Sung (宋岡哲)" <notifications@github.com> wrote:

> @GitMensch Is there any regression with my change in c14a8c38693e8c91a47e955648a56cff707b70d4 when building in MinGW, or is your complaint exactly the same as what I addressed in #185?
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/188#issuecomment-282459314

-- 
Will Estes
westes575@gmail.com

**Comment by GitMensch** [comment]
It was the main point of #185 - if you provide a nightly tarball (I don't have the tools for running `autogen.sh` in this environment) I'll recheck but think this is fine now.

**Comment by GitMensch** [comment]
Just a note, I think it would be better to change `autogen.sh`:

```diff
-libtoolize --install --force || glibtoolize --install --force
+libtoolize --install --force || glibtoolize --install --force || echo "error: libtoolize missing" && exit 1
```

**Comment by Explorer09** [comment]
@GitMensch I would say you missed a pair a braces on that statement:

```
-libtoolize --install --force || glibtoolize --install --force || echo "error: libtoolize missing" && exit 1
+libtoolize --install --force || glibtoolize --install --force || { echo "error: libtoolize missing" && exit 1;}
```

**Comment by GitMensch** [comment]
@Explorer09 you're version looks fine, next step would be the pull request ;-)

**Comment by GitMensch** [comment]
... changed the script and put it into a pull request: https://github.com/westes/flex/pull/198

**Comment by GitMensch** [comment]
Just a note: I've run `make dist` on another machine now and can confirm that configure checks this as it should:

~~~
checking regex.h usability... no
checking regex.h presence... no
checking for regex.h... no
configure: error: required header not found on your system
~~~
