### PR TITLE
flex 3.0

### PR DESCRIPTION
**Pull request by egorpugin**
Build system is moved to CMake. Full crossplatform support (win/*nix). autotools support was dropped.
Flex sources are moved to C++14. Only internal change for easier maintenance. Flex is still able to generate C/C++/... files.
m4 dependency is dropped. 'simple_m4' implementation is added as a replacement.
travis and appveyor CI were added.
many changes are cherry-picked from main branch to be tied with the latest changes.

All test suite is passing. See
https://travis-ci.org/egorpugin/flex/builds/143611715
https://ci.appveyor.com/project/egorpugin/flex/build/1.0.120

### CODE REVIEW

**Comment by AlexanderS** [comment]
This contains many commits from the master branch, because you merged your branch with upstream. Can you maybe rebase your changes?

**Comment by westes** [comment]
This is several changes rolled into one. Please do some things to make this easier to digest:

- split this into its component parts.
- rebase your commits of master instead of merging them.
- squash your commits so that your fixups aren't showing as separate commits.

**Comment by DemiMarie** [comment]
Could the issues regarding `[[` and `]]` be resolved by this patch?  Or does Flex already perform adequate escaping?  (This can be done by replacing `]` with `]]][[` and `[` with `[]][[` everywhere, assuming that the input text is always in quotes, or by switching quoting to (say) `[<`/`>]` and escaping `[<` as `[>][<<` and `>]` as `>>][<]`).

**Comment by egorpugin** [comment]
@AlexanderS, @westes Done.
@DemiMarie Actually the functionality was not changed. Please, give an example, so we could check.

**Comment by DemiMarie** [comment]
@egorpugin #79 is one problem due to inadequate quoting; there are almost certainly others.

**Comment by DemiMarie** [comment]
This fails to bootstrap for me.

**Comment by egorpugin** [comment]
Please, provide logs.
This PR has conflicts now with master branch, because of your commits. I'll fix this later.

**Comment by Explorer09** [comment]
Um. Allow me to ask, what the rationale of removing autotools support and depending solely on CMake to build? I believe this would trouble many distro or toolchain builders (including projects like Linux From Scratch) as dependency on CMake will become mandatory. So I'm asking why.

And since this pull request is titled "flex 3.0", is this / will this be the official direction of flex? (If not, the title seems misleading to me.)

**Comment by egorpugin** [comment]
Why? - Lesser maintenance costs; windows support.

**Comment by westes** [comment]
It is a proposal. I'm unfamiliar with cmake and how it works, so it is one thing I will have to look into -- among many others -- whether or not it effects builders / distributors in various ways. That being said, I'd think that distributors would simply use whatever tools  were required. The advantage, as describe to me, is that cmake works out of the box on MSWindows. Beyond that, I will have to investigate many things.

Is it going to be flex 3.0? I don't know that. It's a large change to the codebase, so the sense was to have this be "not for right now".

**Comment by egorpugin** [comment]
Also I'm thinking now about supporting this PR or fork, so-called flex 3.0, myself.
I'll port flex 2.x changes and keep the fork with upstream, so we could merge anytime later.

**Comment by DemiMarie** [comment]
Your branch currently fails to bootstrap and produces a truncated output
file.

**Comment by egorpugin** [comment]
Steps to reproduce?
My branch passes all tests and works fine.
https://travis-ci.org/egorpugin/flex/builds/143611715

**Comment by DemiMarie** [comment]
Doesn't work with CMake 3.5.2 and either G++ 6.2.1 or Clang++ 3.8:

```
libcommon.a(flexmain.cpp.o): In function `flexinit(int, char**)':
/home/dobenour/repos/flex-3.0-unchanged/src/flexmain.cpp:(.text+0x4ae6): undefined reference to `set_input_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/dobenour/repos/flex-3.0-unchanged/src/flexmain.cpp:(.text+0x4b06): undefined reference to `set_input_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libcommon.a(gen.cpp.o): In function `make_tables()':
/home/dobenour/repos/flex-3.0-unchanged/src/gen.cpp:(.text+0x8a0d): undefined reference to `flexscan()'
libcommon.a(yylex.cpp.o): In function `yylex()':
/home/dobenour/repos/flex-3.0-unchanged/src/yylex.cpp:(.text+0xf): undefined reference to `flexscan()'
/home/dobenour/repos/flex-3.0-unchanged/src/yylex.cpp:(.text+0x1c6): undefined reference to `yytext'
/home/dobenour/repos/flex-3.0-unchanged/src/yylex.cpp:(.text+0x283): undefined reference to `yytext'
clang-3.8: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by egorpugin** [comment]
See http://pastebin.com/aQNH6r7n - 0 build errors (0 test errors too, not shown in log).
Command `git clone https://github.com/egorpugin/flex && cd flex && mkdir build && cd build && cmake .. && make -j8`

**Comment by DemiMarie** [comment]
Still same error on my side.

**Comment by DemiMarie** [comment]
I'm stuck.  Here is a Perl script that reproduces the error from a fresh checkout

```perl
#!/usr/bin/env perl 
#===============================================================================
#
#         FILE: build.pl
#
#        USAGE: ./build.pl  
#
#  DESCRIPTION: Build Flex 3.0
#
#      OPTIONS: ---
# REQUIREMENTS: ---
#         BUGS: ---
#        NOTES: ---
#       AUTHOR: YOUR NAME (), 
# ORGANIZATION: 
#      VERSION: 1.0
#      CREATED: 10/25/2016 11:44:18 PM
#     REVISION: ---
#===============================================================================

use strict;
use warnings;
use utf8;

%ENV = (PATH => '/usr/bin:/bin');

if ($0 =~ /\//) {
    # The r flag ensures that a copy is returned
    chdir $0 =~ s|/[^/]*|/|r or die "chdir failed: $!";
}
mkdir 'build';
chdir 'build' or die $!;
system 'cmake', '..', '-DCMAKE_BUILD_TYPE=Debug', '-GNinja' and die $!;
exec 'ninja-build';
exec 'ninja';
die $!;
```

**Comment by egorpugin** [comment]
Ninja builds do not work. Ninja does not respect all cmake statement and skip them.

**Comment by DemiMarie** [comment]
This Perl script also fails:

```perl
#!/usr/bin/env perl 
use strict;
use warnings;
use utf8;

%ENV = (PATH => '/usr/bin:/bin');

if ($0 =~ /\//) {
    # The r flag ensures that a copy is returned
    chdir $0 =~ s|/[^/]*|/|r or die "chdir failed: $!";
}
system qw(rm -rf build) and die $!;
mkdir 'build' or die $!;
chdir 'build' or die $!;
system qw(cmake .. -DWITH_TESTS=1
          -DCMAKE_C_COMPILER=/usr/bin/clang
          -DCMAKE_CXX_COMPILER=clang++) and die $!;
system 'make' and die "Exit code $?";
exec 'ctest';
die $!;
```
with the error message:
```
libcommon.a(flexmain.cpp.o): In function `flexinit(int, char**)':
/home/dobenour/repos/flex-3.0-u2/src/flexmain.cpp:(.text+0x3fa0): undefined reference to `set_input_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/dobenour/repos/flex-3.0-u2/src/flexmain.cpp:(.text+0x3fd6): undefined reference to `set_input_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libcommon.a(gen.cpp.o): In function `make_tables()':
/home/dobenour/repos/flex-3.0-u2/src/gen.cpp:(.text+0x9af2): undefined reference to `flexscan()'
libcommon.a(yylex.cpp.o): In function `yylex()':
/home/dobenour/repos/flex-3.0-u2/src/yylex.cpp:(.text+0x26): undefined reference to `flexscan()'
/home/dobenour/repos/flex-3.0-u2/src/yylex.cpp:(.text+0x5dd): undefined reference to `yytext'
/home/dobenour/repos/flex-3.0-u2/src/yylex.cpp:(.text+0x609): undefined reference to `yytext'
clang-3.8: error: linker command failed with exit code 1 (use -v to see invocation)
src/CMakeFiles/flexmain.dir/build.make:99: recipe for target 'bin/flex' failed
make[2]: *** [bin/flex] Error 1
CMakeFiles/Makefile2:712: recipe for target 'src/CMakeFiles/flexmain.dir/all' failed
make[1]: *** [src/CMakeFiles/flexmain.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
```

**Comment by egorpugin** [comment]
Could you send full log, please?
And try to change
```
-DCMAKE_C_COMPILER=/usr/bin/clang
-DCMAKE_CXX_COMPILER=clang++
```
to 
```
-DCMAKE_C_COMPILER=clang
-DCMAKE_CXX_COMPILER=clang++
```

Also try to `rm -rf flex-dir` and re-clone it from github again.

**Comment by DemiMarie** [comment]
The build script (same as above, except for comments and some more verbose error messages) is [here][build.pl].  The logs (combined stderr and stdout) are [here][log.txt].

[build.pl]: https://gist.github.com/DemiMarie/b7a1498b1e458a05e20b302a92294b39
[log.txt]: https://gist.github.com/DemiMarie/c91b0ee436565442314d28e9ecd93b75

**Comment by DemiMarie** [comment]
Also, I believe the current build set-up is incompatible with cross-compilation.

**Comment by egorpugin** [comment]
Yes, but it's easy to fix.
As for our investigations could you please post files: `bld_dir/src/scan.cpp` and `bld_dir/src/stage1.scan.cpp`?
For me they are almost the same. But in your case linker for some reasons does not see symbols from that object file (2nd one).

**Comment by DemiMarie** [comment]
[stage1scan.cpp] (looks normal).
[scan.cpp] (appears truncated).

[stage1scan.cpp]: https://gist.github.com/DemiMarie/f109313c9eafdbaf36407dbcaca1c5b2
[scan.cpp]: https://gist.github.com/DemiMarie/0b3c15f5eb3db7b9cd51eeb70f82d5eb

**Comment by egorpugin** [comment]
Uh-oh. Those links are broken.

**Comment by egorpugin** [comment]
Yeah, that's the issue. Thanks! I'll try to investigate it with your scripts.

**Comment by DemiMarie** [comment]
Thanks!

**Comment by egorpugin** [comment]
Ok, I tried your script in form:
```
#!/usr/bin/env perl 

use strict;
use warnings;
use utf8;

%ENV = (PATH => '/usr/bin:/bin');

system qw(rm -rf build) and die "deleting build dir failed\n";
mkdir 'build' or die "mkdir failed: $!\n";
chdir 'build' or die "chdir failed: $!\n";
system qw(cmake .. -DWITH_TESTS=1
          -DCMAKE_BUILD_TYPE=Debug
          -DCMAKE_C_COMPILER=clang
          -DCMAKE_CXX_COMPILER=clang++) and die "cmake failed: exit code $!\n";
system qw(make -j10) and die "make failed: exit code $?\n";
exec 'ctest';
die "exec failed: $!\n";
```

It works fine. Build is ok and all tests passed. Probably the issue somewhere in your environment.
Could you try an inline command again but with clang as a compiler this time:
`git clone https://github.com/egorpugin/flex && cd flex && mkdir build && cd build && cmake .. -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang && make -j8`

**Comment by DemiMarie** [comment]
Same error message.

**Comment by DemiMarie** [comment]
I don't think it is an environment variable – that would not fool the Perl
script, which explicitly sets the environment.

Do you have any suggestions for debugging?

**Comment by egorpugin** [comment]
Do you have any other machines or places to test? Maybe try there?
Because for me it works perfect on win/linux/macos, travis-ci.

For debug you should use -DCMAKE_BUILD_TYPE=Debug as parameter to cmake.
Then call `stage1flexmain -o "scan.cpp" "src/scan.l"` and check `scan.cpp` output. If it's empty  again go ahead with your favourite ide or gdb and debug this binary for when it stops printing output file.

**Comment by DemiMarie** [comment]
@westes Can you (or someone else) try this PR and see if it builds?

**Comment by evelikov** [comment]
Disclaimer: I'm not involved with flex so keep that in mind. None of my comments suggest "this work is sh*t/useless/etc" but points out that there's hundreds of devs. which this will have impact on. Consider (and document) it wisely.

Note for the maintainer: I'd encourage you to reach out to distributions (some at least) before going forward.

There are two distinct things - build system and coding language. Neither of which has any technical justification other than "it's new and cool" sort of reasoning.

On the build:
 - One _can_ use autoconf in Windows env via MSYS. A number of projects use it and CI such as AppVeyor (iirc) offer it.
 - Moving to cmake will effectively force every BSD to revert/rewrite the lot. flex is in the "base" system which does not (in not allowed to?) use cmake.
 - cmake (by default) does not provide self contained tarballs - maybe the implementation here provides that alongside all the other useful targets that you get with autoconf - install, uninstalls, cscope, ctags etc.

Code wise:
 - Not everyone can use C++14 compiler, despite how much they'd love to.
 - Any build system supports mixing C and CPP sources into the final binary. Redoing some 10kloc in one go is just silly.
 - From a _very_ quick look there is nothing specific that stands out with the C++ codebase - would that be  #loc, performance improvement (compile or runtime) or any C++ feature that makes coding easier/faster.

**Comment by egorpugin** [comment]
You are right. PR might look questionable.
Real conflict here is `C itselft, C build tools, C world` vs. `C++, C++ build tools (common or not), C++ world`. And also probably platforms that do not support C++ at all (the strongest argument against this PR).

Gcc 6 has C++14 by default, so this leaves us a question about build tools.
C and C projects are cool but too many of them are repeating each other in terms of standard features (e.g. strings), containers (like (hash) maps), memory management, algorithms what already exists in C++ STL. Also add build system to this list (ac macros, m4). Those projects who does not like to repeat each other use Gnulib (in GNU GPL world). Gnulib itself is an attempt to create more or less standardized set of features written in C.

When discussing this PR with Will privately I said that it's possible to maintain same level of features in both versions: old good `2.x.x` and "modern" `3.x.x`.

ps.
I'm not pushing this forward really hard.
Maybe for some people it's just like "Hey, we have C++ flex here. Maybe somewhen we could try it."
