### ISSUE TITLE
v2.6.2 introduces behavior change that is incompatible with previous versions

### ISSUE THREAD

**Issue by nvinson** [westes/flex#113]
With version 2.6.1 if prefix was set, then all affected functions would have their declaration changed and all references in the lexer input file would be changed as well.  With v2.6.2 only the function declarations are changed.

For example, set prefix to AA, reference yyget_extra() in the lexer input file, and build the C file using v2.6.1 and all calls in the C source file will be to AAget_extra().  However, build with v2.6.2 and the resultant C file will still have calls to yyget_extra() resulting in a broken source file.

This change in behavior appears to have been introduced with commit ee87e5df0056671be04eefaaeb85979d7bfca89c.

**Comment by Polynomial-C** [comment]
Consequences of this change can be searched and found here: https://bugs.gentoo.org/598186

**Comment by fabled** [comment]
Flex 2.6.2 also does not properly handle doxygen. The flex generated code fails with:

> [ 23%] Building CXX object qtools/CMakeFiles/qtools.dir/qregexp.cpp.o
> configimpl.l:692:32: error: stray '\' in program
>  <Start>[a-z_A-Z][a-z_A-Z0-9]*[ \t]*"+=" { QCString cmd=yytext;
> configimpl.l: In function 'int configimplYYlex()':
> configimpl.l:692:1: error: expected primary-expression before '<' token
>  <Start>[a-z_A-Z][a-z_A-Z0-9]*[ \t]*"+=" { QCString cmd=yytext;
>  ^
> configimpl.l:692:9: error: 'a' was not declared in this scope
>  <Start>[a-z_A-Z][a-z_A-Z0-9]*[ \t]*"+=" { QCString cmd=yytext;
>          ^
> configimpl.l:692:10: error: expected ',' before '-' token
>  <Start>[a-z_A-Z][a-z_A-Z0-9]*[ \t]*"+=" { QCString cmd=yytext;
>           ^
> configimpl.l:692:10: error: expected identifier before '-' token
> configimpl.l: In lambda function:
> configimpl.l:692:17: error: expected '{' before '[' token
>  <Start>[a-z_A-Z][a-z_A-Z0-9]*[ \t]*"+=" { QCString cmd=yytext;
>                  ^
> configimpl.l: In function 'int configimplYYlex()':
> configimpl.l:692:20: error: 'z_A' was not declared in this scope
>  <Start>[a-z_A-Z][a-z_A-Z0-9]*[ \t]*"+=" { QCString cmd=yytext;
>                     ^~~
> configimpl.l:692:24: error: 'Z0' was not declared in this scope
>  <Start>[a-z_A-Z][a-z_A-Z0-9]*[ \t]*"+=" { QCString cmd=yytext;
>                         ^~
> configimpl.l:692:33: error: 't' was not declared in this scope
>  <Start>[a-z_A-Z][a-z_A-Z0-9]*[ \t]*"+=" { QCString cmd=yytext;
>                                  ^
> configimpl.l: In lambda function:
> configimpl.l:692:35: error: expected '{' before '*' token
>  <Start>[a-z_A-Z][a-z_A-Z0-9]*[ \t]*"+=" { QCString cmd=yytext;
>                                    ^

The code it generated looks like:
>                                         }
> <Start>[a-z_A-Z][a-z_A-Z0-9]*[ \t]*"+=" { QCString cmd=yytext;
>                                           cmd=cmd.left(cmd.length()-2).stripWhiteSpace(); 
>                                           ConfigOption *option = config->get(cmd);
>                                           if (option==0) // oops not

Basically it did not handle the pattern match at all.

**Comment by tarceri** [comment]
Just to add another me too. This issue breaks Mesa also: https://bugs.freedesktop.org/show_bug.cgi?id=98473

**Comment by tgurr** [comment]
It also breaks kde-frameworks/kservice: https://bugs.kde.org/show_bug.cgi?id=371885 and the developers comment was "So why not report this to the flex authors?".

**Comment by westes** [comment]
@DemiMarie, could you have a look at this?

**Comment by nvinson** [comment]
I just tested head against nftables-0.6 (using Gentoo's nftables-0.6-r4 ebuild) and the issue is still present.  Could you please reopen this bug until the issue is fixed?

**Comment by westes** [comment]
Certainly. @DemiMarie, what do you think?

**Comment by DemiMarie** [comment]
I think I know what is going on.

Flex versions <= 2.6.1 expand M4 macros in the source file.  This allows a bad input file to execute arbitrary shell commands and results in broken debugging info.  It also corrupts string literals that happen to contain the relevant strings.

I "fixed" this behavior.  This also required changing the testsuite.  In retrospect, I should probably have realized that this would break code.

The solution is to add CPP (_not_ M4) macros that handle this.  I will make a patch.

**Comment by DemiMarie** [comment]
If the problem is in section 3, you can use `--unsafe-no-m4-sect3-escape` as a temporary workaround.

**Comment by DemiMarie** [comment]
@nvinson Can you see if #123 fixes this?

**Comment by nvinson** [comment]
> @nvinson Can you see if #123 fixes this?

nftables compiled with that change.  I'll do more extensive testing later this week.

**Comment by Polynomial-C** [comment]
@westes Can we please have a new release once this issue has been confirmed to be fixed?

**Comment by MarcinWieczorek** [comment]
Hi guys, I'm having trouble with flex.
Here's my build log, read the bottom please:
http://sprunge.us/dTKi
Do you think it's related?
