### ISSUE TITLE
flex-2.6.1 breaks lilypond-2.18.2

### ISSUE THREAD

**Issue by 0-wiz-0** [westes/flex#124]
lilypond-2.18.2 (available from http://lilypond.org/) builds fine with flex-2.6.0, but with flex-2.6.2 the build fails with:
````
out/lexer.cc: At global scope:
out/lexer.cc:6433:25: error: expected constructor, destructor, or type conversion before '(' token
 yyFlexLexer::yyFlexLexer( FLEX_STD istream* arg_yyin, FLEX_STD ostream* arg_yyout ):
                         ^
````

**Comment by westes** [comment]
And to be clear, the build works with 2.6.1?

**Comment by 0-wiz-0** [comment]
Hadn't tried that before, but did just now, and got the same error with 2.6.1 as with 2.6.2.

**Comment by westes** [comment]
Yes, once we've got more confirmation, I will put out another release that includes the fix.

**Comment by 0-wiz-0** [comment]
Which commit(s) contain(s) the fix?

**Comment by westes** [comment]
Ack, I commented on the wrong issue.

A couple questions: Why does lilypond need flex? As distributed, it should include the lexer. (Notwithstanding that this is a bug that needs fixed.)

Do we know at what point flex was able to build this?

**Comment by 0-wiz-0** [comment]
Not sure why it uses flex.
With flex-2.6.0 it builds fine.

**Comment by 0-wiz-0** [comment]
I looked at the diff between 2.6.0 and 2.6.1 and did a lucky guess. Applying this patch to 2.6.2 (revert of a diff between 2.6.0 and 2.6.1) fixes the lilypond build for me:
````
--- src/FlexLexer.h.orig        2016-10-21 00:43:44.000000000 +0000
+++ src/FlexLexer.h
@@ -49,6 +49,9 @@
 #define __FLEX_LEXER_H
 
 #include <iostream>
+#  ifndef FLEX_STD
+#    define FLEX_STD std::
+#  endif
 
 extern "C++" {
 
````
I grepped the lilypond source tree but didn't find "FLEX_STD" before the build.
After the build the symbol appears here:
````
out/lexer.cc:yyFlexLexer::yyFlexLexer( FLEX_STD istream* arg_yyin, FLEX_STD ostream* arg_yyout ):
````

I don't understand where that's coming from, so I don't know why it works or is needed.
Does this help?

**Comment by westes** [comment]
Yes it does. I remember why that commit was made, so as usual, C(++) macros play havoc in unexpected ways. I'll have to dig to figure out what the best thing to do is, but if nothing else, we have a work around. The FLEX_STD symbol is not something that a flex-using-app would define. It is/was a symbol to work around the fact that the std:: stuff didn't used to be present everywhere.

**Comment by westes** [comment]
There's the commit e666829. Does that fix this issue?

**Comment by 0-wiz-0** [comment]
That commit does not even seem to be needed; I just tried with 2.6.3 and it worked. Thanks!
